### ISSUE TITLE
Getting error d.getMonth is not a function?

### ISSUE THREAD

**Issue by lokopinagar** [agschwender/jquery.formatDateTime#6]
I am formatting datetime like following:

 $.formatDateTime('mm/dd/yy', $("#DateOfBirthHidden").val())
but it gives me error "d.getMonth is not a function"

I am using "jQuery v1.9.1 | (c) 2005, 2012 jQuery Foundation, Inc."

Thanks

**Comment by agschwender** [comment]
You're calling it incorrectly. When called this way, you need to pass the date as a `Date` object. I'm guessing that you're passing it as a string.

So you'd want to call it like so:

``` javascript
$.formatDateTime('mm/dd/yy', new Date($('#DateOfBirthHidden').val()));
```
